title: personal notes
author:
  name: Devin Chen
  email: your-email@domain.com
description: >
  Full Stack Engineer at Grab

show_excerpts: false # set to true to show excerpts on the homepage
# Build settings
baseurl: "" # the subpath of your site, e.g. /blog
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

header_pages:
  - about.md

#
# Below are old settings
#

url: "https://xx7y7xx.github.io" # the base hostname & protocol for your site
github_username: xx7y7xx
google_analytics: G-WQ0NM9KGYD

# Build settings
# Github Recommended Settings
markdown: kramdown

# Blog Settings
#lang: en
#domain: xx7y7xx.github.io
#title: xx7y7xx
#tagline: ':(){:|:&amp;};:'

# Use Gemfile to manage gems.
#gems:
#- jekyll-sitemap
#- jekyll-plantuml

#plugins_dir:  ./_plugins

#defaults:
#  -
#    scope:
#      path: "" # an empty string here means all files in the project
#      type: "pages"
#    values:
#      layout: "page"

exclude: ["Gemfile.lock", "Gemfile"]

keep_files: ["README.md"]

include: ["_pages"]
