# name: Check 404

# on:
#   workflow_dispatch:
#   schedule:
#     - cron: "0 8 * * 5" # every friday AM 8:00

# jobs:
#   broken_link_checker_job:
#     runs-on: ubuntu-latest
#     name: Check for broken links
#     steps:
#       - name: Check for broken links
#         id: link-report
#         uses: celinekurpershoek/link-checker@v1.0.2
#         with:
#           # Required:
#           url: "https://xx7y7xx.github.io/"
#           # optional:
#           honorRobotExclusions: false
#           #ignorePatterns: "github,google"
#           recursiveLinks: true # Check all URLs on all reachable pages (could take a while)
#       - name: Get the result
#         run: echo "${{steps.link-report.outputs.result}}"

name: Markdown lint

on:
  workflow_dispatch:
#   push:
#     branches: [ main ]
#   pull_request:
#     types: [assigned, opened, synchronize, reopened]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'restqa-404-links'
      uses: restqa/404-links@3.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
